### ISSUE TITLE
max-width/max-height should be able to handle measurements other than pixels

### ISSUE THREAD

**Issue by elwayman02** [paddle8/ember-autoresize#13]
Some users may want to be able to pass in a different form of measurement than a number that will be interpreted in px.  They may want to use em or some other option for their max-width/max-height.  The mixin should be able to interpret multiple forms of input for the styling.

**Comment by tim-evans** [comment]
That should be reasonable to do. Would you like to write a PR to implement this?

The only thing that I think needs to be changed is appending 'px' if the value has no units

**Comment by elwayman02** [comment]
Yea, I can take a look at it :)

**Comment by elwayman02** [comment]
@tim-evans there is some stuff in measuredSizeDidChange and dimensionsDidChange that expects the bound attribute to always be a number.  I haven't had a chance to look at it in depth, but that might be something for you to investigate if you get the chance.  If I get a branch up that has the base changes for this issue, can you dig deeper on those two methods and push this across the finish line?

**Comment by elwayman02** [comment]
https://github.com/elwayman02/ember-autoresize/tree/variable-units

**Comment by tim-evans** [comment]
I've published `0.4.0`, which supports this. If you spin up the addon with `ember server`, you should see a test page that I used to verify these. Close this when you think it's all good :)

Thanks for the help on this- it was a great addition to the addon!

**Comment by elwayman02** [comment]
Great! I will check it out.

**Comment by elwayman02** [comment]
Looks good, will test further in the morning :)

**Comment by elwayman02** [comment]
Hmm...initial testing indicates the addon is broken now.  Textarea resizing isn't working at all for me.

**Comment by tim-evans** [comment]
@elwayman02 confirmed. This is only in the 'auto' case.

**Comment by tim-evans** [comment]
Aaaand fixed!

**Comment by elwayman02** [comment]
:shipit:

**Comment by elwayman02** [comment]
@tim-evans line 306 automatically appends 'px' to the keys...will that cause an issue with this feature?

**Comment by tim-evans** [comment]
@elwayman02 nope! The `dimensions` property is a result of the dom-ruler measurement
