### ISSUE TITLE
Eliminate the need for ember g

### ISSUE THREAD

**Issue by elwayman02** [paddle8/ember-autoresize#15]
There should be a way for the addon to automatically execute its own blueprint during install, rather than having to make the user run ```ember g ember-autoresize``` afterward.  I just don't remember what it is, lol.

**Comment by tim-evans** [comment]
The installation should say `ember install ember-autoresize`, that's the problem.

**Comment by elwayman02** [comment]
The generate command doesn't run even then, I tried it

**Comment by tim-evans** [comment]
I don't think this is an issue anymore. :)

Hopefully ember-cli fixes this.
