### ISSUE TITLE
0.4.0 is broken

### ISSUE THREAD

**Issue by elwayman02** [paddle8/ember-autoresize#16]
@tim-evans is it working for you?  autoresize seems to be completely broken from my testing

**Comment by tim-evans** [comment]
My tests worked. Could you provide more info on "not working"?

What version of ember-cli are you using / ember, and if you're getting any errors what are they?

**Comment by tim-evans** [comment]
Sorry about that- check on 0.4.1

**Comment by elwayman02** [comment]
Fixed!
