### ISSUE TITLE
Resolve deprecations

### ISSUE THREAD

**Issue by bcardarella** [paddle8/ember-autoresize#17]
Ember 1.12 started to throw Deprecation warnings. Resolving this will break backwards compatibility so you should be aware of this when bumping the version of this library to resolve this issue.

https://github.com/paddle8/ember-autoresize/blob/master/addon/mixins/autoresize.js#L63

should be rewritten as:

```javascript
atuoresize: computed('', {
  set: function(keyname, value) {
     ...
  }
})
```

See: http://emberjs.com/deprecations/v1.x/#toc_computed-properties-with-a-shared-getter-and-setter

**Comment by tim-evans** [comment]
@bcardarella Yeah, I think I'll bump to a major version when I want to remove all the old stuff.

**Comment by discorick** [comment]
+1 on resolving the deprecations, especially to pave the way for 1.13 & 2.0

**Comment by tim-evans** [comment]
I would need to know who's using older versions of get and set before I fix this.

**Comment by tim-evans** [comment]
I'm gonna release a new major version and provide a note letting users using < 1.12 to use the last version published.
