### ISSUE TITLE
No way to set a default value unless autoResizeText configurable?

### ISSUE THREAD

**Issue by JKGisMe** [paddle8/ember-autoresize#22]
I would like to have it use the placeholder, or be able to give it a string to use in case the placeholder is not being used. Is there a way to do that? I tried a few things but nothing seems to work. I apologize if I'm missing something obvious, as is often the case with me!

I'm doing something like this on focusOut to ensure the field always has a value but it seems the textfield resizes to only fit `.` from autoResizeText and doesn't resize to accommodate the text being inserted: 

```javascript
if(this.$('input').val()===''){
        this.$('input').val('default value');
    }
```

If I could set the autoResizeText property directly or the value it uses then it would be perfect.

**Comment by tim-evans** [comment]
Thanks for the PR! This is available for 0.5.3. (Keep in mind that this doesn't work on 2.0.0 yet)
