### ISSUE TITLE
Add class to identify temporary div

### ISSUE THREAD

**Issue by mayatron** [paddle8/ember-autoresize#8]
Would be nice to have a class name to identify the temporary div that's created. Just spent a little while trying to figure out where this div was coming from. So, for example:

`<div class="ember-autoresize" style="position: absolute; left: -10010px; top: -10px; width: 10000px; height: 0px; overflow: hidden; visibility: hidden;">`

Thanks for your work on this.

**Comment by tim-evans** [comment]
Good idea! I'll do this myself or would happily take a PR

**Comment by tim-evans** [comment]
This is in a sub-library, dom-ruler, so I'm closing this. I'm adding an id of "dom_ruler-text_measurer" to the element, since it's a singleton.

**Comment by tim-evans** [comment]
@mayatron (the most recent release 0.3.0 solves this issue)
